### ISSUE TITLE
Panorama theme

### ISSUE THREAD

**Issue by ReaVeNx47** [unburn/greetify#2]
```
const card = await Panorama({
      name: member.user.username,
      avatar: member.user.displayAvatarURL({ size: 4096, format: "png" }),
      type: title,
});

```

Error: remote source rejected with status code 404
    at /root/dev/node_modules/cropify/dist/index.js:90:11
    at Generator.throw (<anonymous>)
    at rejected (/root/dev/node_modules/cropify/dist/index.js:30:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by UnschooledGamer** [comment]
Found the issue I'll fix it as soon as I get free, For now you can provide a `backgroundImage` property and continue using it.
